### ISSUE TITLE
关于实验结果和论文结果的问题

### ISSUE THREAD

**Issue by PrimaLuz** [cambridgeltl/eva#5]
你好，我在复现你的代码时发现结果分为“l2r”和“r2l”两个方向，论文里只有一个方向，比如DBP15Kzh-en。请问论文里的结果是否是实验中“l2r”+“r2l”求平均得来的吗？

**Comment by hardyqr** [comment]
你好，文章table1，2，3都有标注alignment的方向，e.g., FR->EN，所以当l是FR，r是EN的时候，应该是看l2r的分数。（但在我印象中两个方向的区别很小）

**Comment by PrimaLuz** [comment]
谢谢你的耐心解释，万分感谢！
